print("Please enter the following information:")

firstname=input("First Name: ")
lastname=input("Last Name: ")
emailaddress=input("Email Address: ")
phonenumber=input("Phone Number: ")
jobtitle=input("Job Title: ")
idnumber=input("ID Number: ")
print(" ")
print(" ")
print("The ID Card Is: ")
print("----------------------------------------")
print(lastname, " ", firstname)
print(jobtitle)
print("ID", idnumber)
print(" ")
print(emailaddress)
print(phonenumber)
print("----------------------------------------")